# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- publish

sast:
  stage: test

include:
- template: Security/SAST.gitlab-ci.yml

.publish:
  image: archlinux:base
  script:
    - pacman -Syu --noconfirm git jre-openjdk-headless
    - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(command -v java))))
    - ./gradlew $module:publishKotlinMultiplatformPublicationToGitLabRepository $module:publishJvmPublicationToGitLabRepository $module:publishJsPublicationToGitLabRepository
  only:
    - tags
  interruptible: false

logger:publish:
  extends: [ .publish ]
  variables:
    module: logger

state:publish:
  extends: [ .publish ]
  variables:
    module: state

cache:publish:
  extends: [ .publish ]
  variables:
    module: cache

backbone:publish:
  extends: [ .publish ]
  variables:
    module: backbone

spine:publish:
  extends: [ .publish ]
  variables:
    module: spine

spine-ktor:publish:
  extends: [ .publish ]
  variables:
    module: spine-ktor

spine-ktor-client:publish:
  extends: [ .publish ]
  variables:
    module: spine-ktor:spine-ktor-client

spine-ktor-server:publish:
  extends: [ .publish ]
  script:
    - pacman -Syu --noconfirm git jre-openjdk-headless
    - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(command -v java))))
    - ./gradlew $module:publishKotlinMultiplatformPublicationToGitLabRepository $module:publishJvmPublicationToGitLabRepository
  variables:
    module: spine-ktor:spine-ktor-server

.test-jvm:
  image: openjdk:latest
  variables:
    module_path: $module
  script:
    - ./gradlew $module:koverReport $module:koverVerify  # implies running the JVM tests
  after_script:
    - mkdir -p test-report-$module_path
    - mv $module_path/build/reports/tests/jvmTest test-report-$module_path/test
    - mv $module_path/build/reports/kover/html test-report-$module_path/coverage
    - mv $module_path/build/reports/kover/xml/report.xml test-report-$module_path/coverage.xml
    - values=$(cat test-report-$module_path/coverage.xml | tail -7 | head -5 | grep 'INSTRUCTION' | cut -d ' ' -f 3,4 | sed 's/missed="//;s/" covered="/ /;s/"\/>//')
    - missed=$(<<<$values cut -d ' ' -f 1)
    - covered=$(<<<$values cut -d ' ' -f 2)
    - echo "Coverage $(($covered * 100 / ($covered + $missed)))%"
  coverage: '/Coverage \d+%/'
  artifacts:
    paths:
      - test-report-$module_path
    expose_as: 'Test and coverage report'
    reports:
      junit: $module_path/build/test-results/jvmTest/**.xml
    when: always
  only:
    - merge_requests
    - main
    - tags
  interruptible: true

.test-jvm-convert-coverage:
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.8
  variables:
    module_path: $module
  script:
    - python /opt/cover2cover.py test-report-$module_path/coverage.xml $CI_PROJECT_DIR/$module_path/src/main/kotlin/ > cobertura.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  only:
    - merge_requests
    - main
    - tags
  interruptible: true

logger:test:jvm:
  extends: [ .test-jvm ]
  variables:
    module: logger

logger:convert-coverage:
  extends: [ .test-jvm-convert-coverage ]
  needs:
    - job: logger:test:jvm
      artifacts: true
  variables:
    module: logger

state:test:jvm:
  extends: [ .test-jvm ]
  variables:
    module: state

state:convert-coverage:
  extends: [ .test-jvm-convert-coverage ]
  needs:
    - job: state:test:jvm
      artifacts: true
  variables:
    module: state

cache:test:jvm:
  extends: [ .test-jvm ]
  variables:
    module: cache

cache:convert-coverage:
  extends: [ .test-jvm-convert-coverage ]
  needs:
    - job: cache:test:jvm
      artifacts: true
  variables:
    module: cache

backbone:test:jvm:
  extends: [ .test-jvm ]
  variables:
    module: backbone

backbone:convert-coverage:
  extends: [ .test-jvm-convert-coverage ]
  needs:
    - job: backbone:test:jvm
      artifacts: true
  variables:
    module: backbone

spine:test:jvm:
  extends: [ .test-jvm ]
  variables:
    module: spine

spine:convert-coverage:
  extends: [ .test-jvm-convert-coverage ]
  needs:
    - job: spine:test:jvm
      artifacts: true
  variables:
    module: spine

spine-ktor:test:jvm:
  extends: [ .test-jvm ]
  variables:
    module: spine-ktor:spine-ktor-server
    module_path: spine-ktor/spine-ktor-server

spine-ktor:convert-coverage:
  extends: [ .test-jvm-convert-coverage ]
  needs:
    - job: spine-ktor:test:jvm
      artifacts: true
  variables:
    module: spine-ktor:spine-ktor-server
    module_path: spine-ktor/spine-ktor-server

dokka:
  image: openjdk:latest
  needs: [ ]
  script:
    - ./gradlew dokkaHtmlMultiModule
    - mv build/dokka/htmlMultiModule documentation
  artifacts:
    paths:
      - documentation
    expose_as: "Documentation"
  interruptible: true

pages:
  image: alpine:latest
  stage: publish
  needs:
    - job: dokka
      artifacts: true
  script:
    - mkdir -p public
    - mv documentation public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
  interruptible: false
